### ISSUE TITLE
Support for Postgresql 11

### ISSUE THREAD

**Issue by Algunenano** [CartoDB/odbc_fdw#68]
In addition of PG10 support (which needs to be merged from `pglsq10-support`) the project isn't compatible with Postgresql 11 due to this change: https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=6337865f36da34e9c89aaa292f976bde6df0b065

Basically `TRUE` and `FALSE` should be changed for `true` and `false`.

**Comment by pramsey** [comment]
I wrapped this into #69 since it doesn't require any special version checking (true/false exist way way back into old PgSQL versions)

**Comment by robe2** [comment]
Anyone try this with released PostgreSQL 11.

It doesn't work for me with released PostgreSQL 11 Stable branche.  (I'll double check to make sure it's not me)

I get this error:

`odbc_fdw.o: In function `odbcExplainForeignScan':
C:\projects\sources\odbc_fdw/odbc_fdw.c:1785: undefined reference to `ExplainPropertyLong'`

**Comment by robe2** [comment]
I think they took out ExplainPropertyLong in 11 perhaps related to this discussion - https://www.postgresql.org/message-id/20180314175853.a5h35zfcetmdwlk4%40alap3.anarazel.de

Here is the commit - https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=f3e4b95edb6cbf0cd41dc9ff0c884bfdc425e6fb   -- so I guess for PostgreSQL 11+ you need to use the Integer version since it now accepts longs.

I'll provide a patch after I compile and do some quick testing.

**Comment by robe2** [comment]
I have pull request - https://github.com/CartoDB/odbc_fdw/pull/82

I was going to reopen this ticket but don't have rights to
